# Generated by Django 4.2 on 2024-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMID', '0003_populate_go_enrich_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='metafilecolumn',
            name='numeric',
            field=models.CharField(choices=[('0', 'String type for the field'), ('1', 'Numeric type for the field')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metafilecolumn',
            name='label',
            field=models.CharField(choices=[('0', 'Not Label'), ('1', 'Label')], max_length=1),
        ),
    ]
