# Generated by Django 4.2 on 2024-03-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMID', '0003_filecolumn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filecolumn',
            unique_together=set(),
        ),
    ]
