# Generated by Django 4.2 on 2024-03-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMID', '0003_sharedfileinstance_label'),
        ('IMID', '0004_populate_go_enrich_data'),
    ]

    operations = [
    ]
