# Generated by Django 4.2 on 2024-03-12 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IMID', '0004_alter_filecolumn_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFileColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cID', models.CharField(max_length=10)),
                ('colName', models.CharField(max_length=50)),
                ('label', models.BinaryField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Uploaded_File_Meta_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FileColumn',
        ),
    ]
